Fixes in GH actions tasks. README badge update

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -32,13 +32,13 @@ jobs:
       run: printf '[defaults]\nroles_path=../' > ansible.cfg
 
     - name: Basic Ansible role syntax check
-      run: ansible-playbook -i tests/inventory --syntax-check tests/${{ matrix.test_play }}
+      run: ansible-playbook -i tests/inventory --syntax-check tests/${{ matrix.test_play }}.yml
 
     - name: Real Ansible run
-      run: ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}
+      run: ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}.yml
 
     - name: Second run to check for indempotence (allowing 5 changes)
-      run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }} | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+      run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}.yml | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
     - name: Test ES with curl
       run: curl http://localhost:9200
