Move file extension to place were playbook names are defined to always have it

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        test_play: ['test-2', 'test-5', 'test-6']
+        test_play: ['test-2.yml', 'test-5.yml', 'test-6.yml']
 
     steps:
 
@@ -32,13 +32,13 @@ jobs:
       run: printf '[defaults]\nroles_path=../' > ansible.cfg
 
     - name: Basic Ansible role syntax check
-      run: ansible-playbook -i tests/inventory --syntax-check tests/${{ matrix.test_play }}.yml
+      run: ansible-playbook -i tests/inventory --syntax-check tests/${{ matrix.test_play }}
 
     - name: Real Ansible run
-      run: ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}.yml
+      run: ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}
 
     - name: Second run to check for indempotence (allowing 5 changes)
-      run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}.yml | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+      run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }} | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
     - name: Test ES with curl
       run: curl http://localhost:9200
