Attempt to fix CI with different conditions per strategy

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -39,8 +39,15 @@ jobs:
         run: ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}
 
       - name: Second run to check for indempotence (allowing 5 changes)
-        run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}"
-        # | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+        run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }} | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+        if: ${{ matrix.test_play != 'test-2.yml' }}
+
+      - name: test-2.yml Second run to check for indempotence (allowing 6 changes)
+        run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }} | grep -q 'changed=6.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+        if: ${{ matrix.test_play == 'test-2.yml' }}
+
+      - name: Wait for ES to be started
+        run: sleep 3
 
       - name: Test ES with curl
         run: curl http://localhost:9200
